spring:
  jpa:
    show-sql: true
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: nsk
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  
#    disable-swagger-default-url: true

plan-api:
 messages:    
  planSaveSuccess: Plan Saved Successfully
  planSaveFail: Plan Save Failed
  planUpdateSuccess: Plan Updated Successfully
  planUpdateFail: Plan Update Failed
  planDeleteSuccess: Plan Deleted Successfully
  planDeleteFail: Plan Delete Failed
  planStatusChange: Plan Status Chnaged Successfully
  PlanStatusFail: Plan Status Change Failed