spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reports
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nsk
    password: nsk23718
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER